#!/bin/bash

options=(
    style=round
    width=6.0
    hidpi=off
    active_color=0xff8080d9
    inactive_color=0xff414550
)

borders "${options[@]}"
borders active_color=0xff8080d9 inactive_color=0xff494d64 width=5.0 &
